//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorkbDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class entry
    {
        public int e_id { get; set; }
        public System.DateTime timestamp { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public string user { get; set; }
        public string solution { get; set; }
    }
}
